#!/usr/bin/env bash
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 currentFirmStats.py
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 currentFirmStats.py
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
python3 RMOfirmSOLO.py -b JohnDRockefellerbot
